<div class="modal fade" role="dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" style="width:400px;">
        <div class="modal-content">
            <form method="post" class="form-permission-card-group-edit">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?=H(empty($errors) ? ($group->id ? T('修改组') : T('添加组')) : T('出错了'))?></h4>
                </div>
                <div class="modal-body" style="padding: 20px 40px;">
                    <input type="hidden" name="id" value="<?=H(isset($form['id']) ? $form['id'] : ($group->id?:''))?>" />
                    <div class="row form-group<?=empty($errors['key'])?'':' has-error'?>">
                        <label class="control-label"><?=H(T('分组标识'))?></label>
                        <input type="text" name="key" class="form-control" value="<?=H(isset($form['key']) ? $form['key'] : ($group->id?:''))?>"/>
                        <?php if (!empty($errors['key'])) {?>
                        <div class="text-danger"><?=H($errors['key'])?></div>
                        <?php }?>
                    </div>
                    <div class="row form-group<?=empty($errors['name'])?'':' has-error'?>">
                        <label class="control-label"><?=H(T('分组名称'))?></label>
                        <input type="text" name="name" class="form-control" value="<?=H(isset($form['name']) ? $form['name'] : ($group->id?$group->name:''))?>"/>
                        <?php if (!empty($errors['name'])) {?>
                        <div class="text-danger"><?=H($errors['name'])?></div>
                        <?php }?>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?=H(T('取消'))?></button>
                    <button type="submit" class="btn btn-primary"><?=H(T('提交'))?></button>
                </div>
            </form>
        </div>
    </div>
</div>
