<div class="board-header" data-require="page/order">
    <div class="board-header-form pull-right text-nowrap" style="margin-top:13px;">
        <input type="text" name="q" class="form-control" style="display:inline-block;width:215px;"/>
        <button class="btn btn-default"><i class="fa fa-fw fa-search"></i></button>
    </div>
    <ul class="board-header-ul list-unstyled">
        <li><a href="review/pending"><?= H(T('待审采购')) ?></a></li>
        <li class="active"><a href="review/done"><?= H(T('审核历史')) ?></a></li>
    </ul>
</div>
