<div class="board-header" data-require="page/order" id="admin-order-review">
    <div class="pull-right" style="margin-top:13px;">
        <div class="dropdown" style="margin-left:40px;margin-right:20px;">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <i class="fa fa-cog" style="margin-right:10px;"></i><span class="caret"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                <li class="show-settings text-center" style="cursor:pointer;"><a href="review/settings"><?= H(T('设置化学品监管类别')) ?></a></li>
            </ul>
        </div>
    </div>
    <div class="board-header-form pull-right text-nowrap" style="margin-top:13px;">
        <form action="ajax/order/review/more/0/<?=H($type)?>">
            <button class="btn btn-default app-q-search-handler pull-right"><i class="fa fa-fw fa-search"></i></button>
            <input type="text" name="q" class="form-control" style="display:inline-block;width:240px;margin-right:10px;" placeholder="<?= H(T('输入订单编号或者商品名称搜索')) ?>" />
        </form>
    </div>
    <ul class="board-header-ul list-unstyled">
        <li <?=$type == 'pending' ? 'class="active"' : '' ?>><a href="review/pending"><?= H(T('待审采购')) ?></a></li>
        <li <?=$type == 'done' ? 'class="active"' : '' ?>><a href="review/done"><?= H(T('审核历史')) ?></a></li>
        <li class="show-settings-tab hide" <?=$type == 'settings' ? 'class="active"' : '' ?>><a href="review/settings"><?= H(T('化学品监管类别设置')) ?></a></li>
    </ul>
</div>
<div class="board-content">
    <?= \Gini\CGI::request("ajax/order/review/more/1/{$type}")->execute()->content() ?>
</div>
