<?php
$vTxtTitle = [
    'hazardous'=> T('危险品'),
    'drug_precursor'=> T('易制毒'),
    'highly_toxic'=> T('剧毒品'),
    'explosive'=> T('易制爆'),
    'psychotropic'=> T('精神药品'),
    'narcotic'=> T('麻醉药品'),
];
$vAllowOperate = ($type=='pending') ? true : false;
?>
<div class="board-content-header">
    <ul class="list-unstyled ul-list clearfix<?=$vAllowOperate ? '' : ' ul-list-noop'?>">
        <li class="ul-list-li-ctime"><?=H(T('创建时间'))?></li>
        <li class="ul-list-li-voucher"><?=H(T('订单编号'))?></li>
        <li class="ul-list-li-product<?=$vAllowOperate?'':' ul-list-li-product-strong'?>"><?=H(T('商品'))?></li>
        <li class="ul-list-li-customer"><?=H(T('买方'))?></li>
        <li class="ul-list-li-vendor"><?=H(T('供应商'))?></li>
        <li class="ul-list-li-price"><?=H(T('金额'))?></li>
        <?php if ($vAllowOperate) {?>
        <li class="ul-list-li-op">&#160;</li>
        <?php }?>
    </ul>
</div>
<div class="board-content-body">
    <?php
    if (count($requests)) foreach ($requests as $vRequest) {?>
        <ul class="list-unstyled ul-list clearfix row<?=$vAllowOperate ? '' : ' ul-list-noop'?>">
            <li class="ul-list-li-ctime"><?=H(date('Y-m-d H:i', strtotime($vRequest->ctime)))?></li>
            <li class="ul-list-li-voucher"><a href="order/review/info/<?=H($vRequest->id)?>"><?=H($vRequest->voucher)?></a></li>
            <li class="ul-list-li-product<?=$vAllowOperate?'':' ul-list-li-product-strong'?>">
            <?php
            $vItems = (array)$vRequest->order_items;
            $tmpI = 1;
            foreach ((array)$vItems as $vPData) {?>
                <?php if ($tmpI++>3) { ?>
                <div>...</div>
                <?php } else { ?>
                <div class="text-ellipsis" title="<?=H($vPData['name'])?> * <?=H($vPData['quantity'])?>">
                    <?php $vCasNO = $vPData['cas_no'];?>
                    <?php if ($vCasNO && $vTypes=\Gini\ChemDB\Client::getTypes($vCasNO)) {?>
                        <?php foreach ((array) $vTypes[$vCasNO] as $vHTs) {?>
                            <?php if (!isset($vTxtTitle[$vHTs])) continue; ?>
                            <span class="product-type product-type-<?=H($vHTs)?>"><?=H($vTxtTitle[$vHTs])?></span>
                        <?php }?>
                    <?php }?>
                    <?=H($vPData['name'])?> * <?=H($vPData['quantity'])?>
                </div>
                <?php }?>
            <?php }?>
            </li>
            <li class="ul-list-li-customer" title="<?=H($vRequest->order_group_title)?>"><?=H($vRequest->order_group_title)?></li>
            <li class="ul-list-li-vendor" title="<?=H($vRequest->order_vendor_name)?>"><?=H($vRequest->order_vendor_name)?></li>
            <li class="ul-list-li-price"><?=H(money_format('%.2n', $vRequest->order_price))?></li>
            <?php if ($vAllowOperate) {?>
            <li class="ul-list-li-op">
                <?php foreach ((array)$vRequest->getAllowedOperators() as $vKey=>$vOp) {?>
                <span class="app-op-per-handler btn btn-link" data-id="<?=H($vRequest->id)?>" data-key="<?=H($vKey)?>"><?=H($vOp['title'])?></span>
                <?php }?>
            </li>
            <?php }?>
        </ul>
    <?php }?>
</div>

<ul class="list-unstyled text-center">
<?php
    $vPFrom = (ceil($page/10) - 1) * 10 + 1;
    $vPTo = min(ceil($page/10) * 10 +1, $total);
    if ($vPT - $vPFrom < 11) {
        $vPFrom = max(1, $vPTo - 11);
    }
?>
<?php if ($vPFrom!=1) {?>
    <li data-page="1" data-type="<?=H($type)?>" class="app-pager-li-handler<?=($page==1) ? ' app-pager-li-active' : ''?>"><?=H(T('首页'))?></li>
<?php }?>
<?php for ($i=$vPFrom; $i<=$vPTo; $i++) {?>
    <li data-page="<?=H($i)?>" data-type="<?=H($type)?>" class="app-pager-li-handler<?=($page==$i) ? ' app-pager-li-active' : ''?>"><?=H($i)?></li>
<?php }?>
<?php if ($vPTo!=$total) {?>
    <li data-page="<?=H($total)?>" data-type="<?=H($type)?>" class="app-pager-li-handler<?=($page==$total) ? ' app-pager-li-active' : ''?>"><?=H(T('尾页'))?></li>
<?php }?>
</ul>
