---
title: ${ADMIN_APP_TITLE}

node: ${MALL_NODE}
debade_secret: ${DEBADE_SECRET}
rpc:
  gateway:
    url: ${GATEWAY_API}
    client_id: ${GATEWAY_CLIENT_ID}
    client_secret: ${GATEWAY_CLIENT_SECRET}
  unitconv:
    url: ${UNITCONV_API}
  chemdb:
    url: ${CHEMDB_API}
#南信工要求增加试剂用途审核可见信息
is_show_order_reagent_purpose: ${ADMIN_ORDER_REVIEW_IS_SHOW_REAGENT_PURPOSE}
is_show_order_instruction: ${ADMIN_ORDER_REVIEW_IS_SHOW_ORDER_INSTRUCTION}
...
