---
default:
  dsn: mysql:dbname=admin_order_review;host=zwj-mysql.docker.local;port=3306
  username: genee
  password: 83719730

hazardous: # 用来获取危化品管理员设置的分级审查信息
  dsn: mysql:dbname=admin_order_review;host=zwj-mysql.docker.local;port=3306
  username: genee
  password: 83719730
...
