<div style="text-align:center;margin-top:20px;">
    <table width="100%">
        <thead>
            <tr>
                <td><span style="font-size:16px;font-weight:900;"><?= H(T('订单编号'))?></span></td>
                <td><span style="font-size:16px;font-weight:900;"><?= H(T('买方'))?></span></td>
                <td><span style="font-size:16px;font-weight:900;"><?= H(T('供应商'))?></span></td>
                <td><span style="font-size:16px;font-weight:900;"><?= H(T('商品'))?></span></td>
                <td><span style="font-size:16px;font-weight:900;"><?= H(T('金额'))?></span></td>
                <td><span style="font-size:16px;font-weight:900;"><?= H(T('操作'))?></span></td>
            </tr>
        </thead>
        <tbody>
            <?php
            if (count($orders)) foreach ($orders as $vID=>$vOrder) {?>
            <tbody>
                <tr>
                    <td><h5><?=H($vOrder->voucher)?></h5></td>
                    <td><h5><?=H($vOrder->customer->name)?></h5></td>
                    <td><h5><?=H($vOrder->vendor_name?:$vOrder->vendor->name)?></h5></td>
                    <td><h5>
                        <?php
                        $vItems = (array)$vOrder->items;
                        $tmpI = 1;
                        foreach ($vItems as $vPData) { ?>
                            <?php $vPData = (array)$vPData ?>
                            <?php if ($tmpI++>3) { ?>
                            <div>...</div>
                            <?php break;} else { ?>
                            <div>
                                <?php $vCasNO = $vPData['cas_no'];?>
                                <?=H($vPData['name'])?> * <?=H($vPData['quantity'])?>
                            </div>
                            <?php }?>
                        <?php }?>
                    </h5></td>
                    <td><h5><?=H(money_format('%.2n', $vOrder->price))?></h5></td>
                    <td><h5><a class="btn btn-primary btn-xs" href="<?= H($url.'/'.$userId.'/'.$vID)?>" target="_blank"><?=H(T('审批'))?></a></h5></td>
                </ul>
            </tbody>
            <?php }?>
        </tbody>
    </table>
</div>

