<div class="modal fade">
    <div class="modal-dialog" style="width:980px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">
                    <?=H(T('订单#:voucher', [':voucher'=> $order->voucher]))?>
                    <span class="status-span"><?=\Gini\ORM\Order::$status_title[$order->status]?></span>
                </h4>
            </div>
            <div class="modal-body">
                <?php
                $group = a('group', (int)$order->group_id);
                $customer_data = [
                    [T('买方'), $order->group->title?:$order->customer->name],
                    [T('买方负责人'), $group->creator->name],
                    [T('下单人'), $order->requester->name?:$order->requester_name],
                ];
                if ($order->idnumber) {
                    $customer_data = [
                        [T('买方'), $order->group->title],
                        [T('买方负责人'), $order->group->creator->name],
                        [T('身份证号'), $order->idnumber],
                    ];
                }
                $vData = [
                    [
                        'title'=> T('供应商'),
                        'data'=> [
                            [T('供应商'), $order->vendor_name?:$order->vendor->name]
                        ]
                    ],
                    [
                        'title'=> T('买方信息'),
                        'data'=> $customer_data,
                    ],
                    [
                        'title'=> T('送货信息'),
                        'data'=> [
                            [T('地址'), $order->address],
                            [T('邮政编码'), $order->postcode],
                            [T('电话'), $order->phone],
                            [T('电子邮箱'), $order->email],
                        ]
                    ],
                ];
                foreach ($vData as $vD) {
                ?>
                <div class="board-info-block">
                    <div class="board-info-block-title"><?=H($vD['title'])?></div>
                    <?php foreach ($vD['data'] as $vDI) {?>
                    <dl style="overflow:hidden;text-overflow:ellipsis">
                        <dt><?=H($vDI[0])?></dt>
                        <dd><?=H($vDI[1])?></dd>
                    </dl>
                    <?php }?>
                </div>
                <?php }?>
                <?php if (\Gini\Config::get('app.is_show_order_instruction') && is_array($order->instruction) && isset($order->instruction['path'])) {
                    $id = $type === 'history' ? $type.'-'.$instance->id : $type.'-'.$task->id;
                ?>
                    <div class="board-info-block">
                        <div class="board-info-block-title"><?=H(T('化学品合法使用说明'))?></div>
                        <div>
                            <dl>
                                <dt><?= H(T('使用说明附件')) ?></dt>
                                <dd>
                                    <?php
                                        echo '<p><a href="review/attach-download/'.$id.'/'.$i.'/'.$index.'/instruction"><i class="fa fa-file"></i><span style="padding:0px 5px;">'.$order->instruction['name'].'</span></a></p>';
                                    ?>
                                </dd>
                            </dl>
                        </div>
                    </div>
                <?php }?>
                <?php
                    $items = $order->items;
                    $item = (array)current($items);
                    if ($item['customized']) {
                    $id = $type === 'history' ? $type.'-'.$instance->id : $type.'-'.$task->id;
                ?>
                <div class="board-info-block">
                    <div class="board-info-block-title"><?=H(T('资质信息'))?></div>
                    <dl style="overflow:hidden;text-overflow:ellipsis">
                        <dt><?= T('营业执照') ?></dt>
                        <dd>
                            <?php
                            foreach ($items as $i => $vItem) {
                                $vItem = (array)$vItem;
                                if ($license_images = $vItem['license_images']) {
                                    foreach ((array)$license_images as $index => $license_image) {
                                        $name = $license_image->name;
                                        echo '<p><a href="review/attach-download/'.$id.'/'.$i.'/'.$index.'/license"><i class="fa fa-file"></i><span style="padding:0px 5px;">'.$name.'</span></a></p>';
                                    }
                                }
                            }
                            ?>
                        </dd>
                    </dl>
                    <dl style="overflow:hidden;text-overflow:ellipsis">
                        <dt><?= T('其他执照') ?></dt>
                        <dd>
                            <?php
                            foreach ($items as $i => $vItem) {
                                $vItem = (array) $vItem;
                                if ($extra_images = $vItem['extra_images']) {
                                    foreach ((array)$extra_images as $index => $extra_image) {
                                        $name = $extra_image->name;
                                        echo '<p><a href="review/attach-download/'.$id.'/'.$i.'/'.$index.'/extra"><i class="fa fa-file"></i><span style="padding:0px 5px;">'.$name.'</span></a></p>';
                                    }
                                }
                            }
                            ?>
                        </dd>
                    </dl>
                </div>
                <?php } ?>

                <div class="board-info-block">
                    <div class="board-info-block-title"><?=H(T('商品清单'))?></div>
                    <div class="row board-table-row board-table-header" style="">
                        <div class="col-xs-3"><?=H(T('商品'))?></div>
                        <div class="col-xs-3"><?=H(T('生产商'))?></div>
                        <div class="col-xs-2"><?=H(T('货号'))?></div>
                        <div class="col-xs-1"><?=H(T('包装'))?></div>
                        <div class="col-xs-1 text-right"><?=H(T('单价'))?></div>
                        <div class="col-xs-1 text-right"><?=H(T('数量'))?></div>
                        <div class="col-xs-1 text-right"><?=H(T('金额'))?></div>
                    </div>
                    <?php foreach ((array)$order->items as $vItem) { ?>
                    <?php $vItem = (array) $vItem;?>
                    <div class="row board-table-row board-table-li">
                        <div class="col-xs-3">
                            <?=\Gini\ORM\Product::showTagsHTML($vItem['product_types'], 'full')?>
                            <?=H($vItem['name'])?>
                        </div>
                        <div class="col-xs-3"><?=H($vItem['manufacturer'])?></div>
                        <div class="col-xs-2"><?=H($vItem['catalog_no'])?></div>
                        <div class="col-xs-1"><?=H($vItem['package'])?></div>
                        <div class="col-xs-1 text-right"><?=H(($vItem['unit_price']==-1) ? T('待询价') : money_format('%.2n', $vItem['unit_price']))?></div>
                        <div class="col-xs-1 text-right"><?=H($vItem['quantity'])?></div>
                        <div class="col-xs-1 text-right"><?=H(($vItem['unit_price']==-1) ? T('待询价') :  money_format('%.2n', $vItem['unit_price'] * $vItem['quantity']))?></div>
                    </div>
                    <?php if ($vItem['customized']) {?>
                    <div class="row board-table-row board-table-li"><div class="col col-xs-12">
                        <?=H(T('自购理由: %reason', ['%reason'=> $vItem['reason']]))?>
                    </div></div>
                    <?php }?>
                    <?php }?>
                    <div class="board-table-footer text-right row board-table-row">
                        <?=H(T('合计: :total', [
                            ':total'=> ($order->price==-1) ? T('待询价') : money_format('%.2n', $order->price)
                        ]))?>
                    </div>
                </div>
                <?php if (\Gini\Config::get('app.is_show_order_purpose') === true && $order->purpose) { ?>
                <div class="board-info-block">
                    <div class="board-info-block-title"><?=H(T('用途'))?></div>
                        <dl style="overflow:hidden;text-overflow:ellipsis">
                            <dt><?=H(T('用途'))?></dt>
                            <dd><?=H($order->purpose)?></dd>
                        </dl>
                    </dl>
                </div>
                <?php  } ?>

                <div class="text-center">
                    <?php if (count($operators)) foreach ($operators as $vKey=>$vOp) {?>
                    <span class="app-op-per-handler btn btn-<?=($vOp['to_status']%2==1) ? 'primary' : 'danger'?>" data-id="<?=H($request->id)?>" data-key="<?=H($vKey)?>"><?=H($vOp['title'])?></span>
                    <?php }?>
                </div>
            </div>
        </div>
    </div>
</div>
