<div class="board-content-header" style="padding:0 20px;">
    <ul class="list-unstyled ul-list clearfix<?=$vAllowOperate ? '' : ' ul-list-noop'?>">
        <li class="ul-list-li-ctime"><?=H(T('时间'))?></li>
        <li class="ul-list-li-voucher"><?=H(T('订单编号'))?></li>
        <li class="ul-list-li-customer"><?=H(T('买方'))?></li>
        <li class="ul-list-li-vendor"><?=H(T('供应商'))?></li>
        <li class="ul-list-li-product"><?=H(T('商品'))?></li>
        <li class="ul-list-li-price"><?=H(T('金额'))?></li>
        <li class="ul-list-li-status"><?=H(T('状态'))?></li>
        <li class="ul-list-li-op"> &#160; </li>
    </ul>
</div>
<div class="board-content-body">
    <?php
    if (count($orders)) foreach ($orders as $vID=>$vOrder) {?>
        <ul class="list-unstyled ul-list clearfix row<?=$vAllowOperate ? '' : ' ul-list-noop'?>">
            <li class="ul-list-li-ctime"><?=H(date('Y-m-d H:i', strtotime($vOrder->ctime)))?></li>
            <li class="ul-list-li-voucher"><a class="app-link-dialog-handler" href="ajax/review/task/<?=$vID?>"><?=H($vOrder->voucher)?></a></li>
            <li class="ul-list-li-customer" title="<?=H($vOrder->group->title)?>"><?=H($vOrder->group->title)?></li>
            <li class="ul-list-li-vendor" title="<?=H($vOrder->vendor_name?:$vOrder->vendor->name)?>"><?=H($vOrder->vendor_name?:$vOrder->vendor->name)?></li>
            <li class="ul-list-li-product">
            <?php
            $vItems = (array)$vOrder->items;
            $tmpI = 1;
            foreach ((array)$vItems as $vPData) {?>
                <?php if ($tmpI++>3) { ?>
                <div>...</div>
                <?php break;} else { ?>
                <div class="text-ellipsis" title="<?=H($vPData['name'])?> * <?=H($vPData['quantity'])?>">
                    <?php $vCasNO = $vPData['cas_no'];?>
                    <?=H($vPData['name'])?> * <?=H($vPData['quantity'])?>
                    <?php if ($vCasNO && $vTypes=\Gini\ChemDB\Client::getTypes($vCasNO)) {?>
                        <?php foreach ((array) $vTypes[$vCasNO] as $vHTs) {?>
                            <?php if (!isset($vTxtTitle[$vHTs])) continue; ?>
                            <span class="product-type product-type-<?=H($vHTs)?>"><?=H($vTxtTitle[$vHTs])?></span>
                        <?php }?>
                    <?php }?>
                </div>
                <?php }?>
            <?php }?>
            </li>
            <li class="ul-list-li-price"><?=H(money_format('%.2n', $vOrder->price))?></li>
            <li class="ul-list-li-status">
                <span class="btn btn-info btn-xs status" data-placement="left" data-preview="instance" data-href="ajax/review/preview/<?=H($vOrder->instance->id)?>"><?=H($vOrder->task_status)?></span>
            </li>
            <li class="ul-list-li-op text-center">
                <span class="app-op-per-handler btn btn-link" data-id="<?=H($vID)?>" data-key="approve"><?=H(T('通过'))?></span>
                <span class="app-op-per-handler btn btn-link" data-id="<?=H($vID)?>" data-key="reject"><?=H(T('拒绝'))?></span>
            </li>
        </ul>
    <?php }?>
</div>

<ul class="list-unstyled text-center">
<?php
    $vPFrom = (ceil($page/10) - 1) * 10 + 1;
    $vPTo = min(ceil($page/10) * 10 +1, $total);
    if ($vPT - $vPFrom < 11) {
        $vPFrom = max(1, $vPTo - 11);
    }
?>
<?php if ($vPFrom!=1) {?>
    <li data-page="1" data-type="<?=H($type)?>" class="app-pager-li-handler<?=($page==1) ? ' app-pager-li-active' : ''?>"><?=H(T('首页'))?></li>
<?php }?>
<?php for ($i=$vPFrom; $i<=$vPTo; $i++) {?>
    <li data-page="<?=H($i)?>" data-type="<?=H($type)?>" class="app-pager-li-handler<?=($page==$i) ? ' app-pager-li-active' : ''?>"><?=H($i)?></li>
<?php }?>
<?php if ($vPTo!=$total) {?>
    <li data-page="<?=H($total)?>" data-type="<?=H($type)?>" class="app-pager-li-handler<?=($page==$total) ? ' app-pager-li-active' : ''?>"><?=H(T('尾页'))?></li>
<?php }?>
</ul>
