<div class="preview-content">
<?php if (!count($comments)) { ?>
    <div class="row"><div class="col-xs-12">
        <?=H(T('暂无审核历史'))?>
    </div></div>
<?php } else { ?>
<div class="status-line">
    <dl class="status-line-content list-unstyled">
        <dt><?=H(T('跟踪信息'))?></dt>
    <?php foreach ($comments as $comment) { ?>
        <dd class="status-line-content-li">
            <div title="<?=H($comment->message)?>"><?=H($comment->message)?></div>
            <div><?=H(T(':group:user:option:date', [
                ':group'=> $comment->group ? $comment->group . ' ' : '',
                ':user'=> $comment->user ? $comment->user. ' ' : '',
                ':option' => $comment->option ? $comment->option. ' ' : '',
                ':date'=> $comment->date? $comment->date. ' ' : ''
            ]))?></div>
        </dd>
    <?php }?>
    </dl>
</div>
<?php } ?>
</div>
